include:
    remote: 'https://github.com/myin142/gitlab-templates/raw/master/basic-nx-test.yml'

stages:
    - test
    - publish

publish:
    stage: publish
    extends: .prepare_nx_affected
    script:
        - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        - npm run publish
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
