image: node

cache:
    paths:
        - node_modules/

only:
    - tags

stages:
    - build
    - publish

build:
    stage: build
    script:
        - npm i
        - npm run build
    artifacts:
        paths:
            - dist/packages

publish:
    stage: publish
    dependencies:
        - build
    script:
        - npm publish dist/packages/aws-cdk
