image: node

cache:
    paths:
        - node_modules/

include:
    - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

before_scripts:
    - npm i

stages:
    - test
    - publish

test:
    stage: test
    script:
        - npm run test

lint:
    stage: test
    script:
        - npm run lint

publish:
    stage: publish
    script:
        - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        - npm run publish
