image: node

.setup_nx_args: &setup_nx_args
  - >
    if [ -z $CI_EXTERNAL_PULL_REQUEST_IID ]; then
      NX_BASE_ARGS="--base $CI_COMMIT_BEFORE_SHA --head $CI_COMMIT_SHA"
    else
      NX_BASE_ARGS="--base $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA --head $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA"
    fi

# have to combine with "npm i" here since anchores do not work across includes
.prepare_nx_affected:
  before_script:
    - npm i
    - *setup_nx_args


cache:
  paths:
    - node_modules/

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


stages:
    - test
    - deploy

test:
    stage: test
    extends: .prepare_nx_affected
    script:
        - npm test -- $NX_BASE_ARGS

lint:
    stage: test
    extends: .prepare_nx_affected
    script:
        - npm run lint -- $NX_BASE_ARGS

deploy:
    stage: deploy
    extends: .prepare_nx_affected
    script:
        - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        - npm run build -- $NX_BASE_ARGS
        - npm run publish -- $NX_BASE_ARGS
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
