image: node

cache:
    paths:
        - node_modules/

stages:
    - build
    - publish

build:
    stage: build
    script:
        - npm i
        - npm run build
    artifacts:
        paths:
            - dist/packages
    only:
        - tags

publish:
    stage: publish
    dependencies:
        - build
    script:
        - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        - npm publish dist/packages/aws-cdk
    only:
        - tags
